# Generated by Django 3.2 on 2021-07-25 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diverty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletas_producto',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diverty.promociones'),
        ),
    ]
